---
title: "[Node.js] Callback Hell은 NEVER! Promise를 활용하자"
layout: post
date: 2017-09-22 18:45
image: /assets/images/profile.jpg
headerImage: false
tag:
- Node.js
star: false
category: blog
author: Terry
description: 콜백지옥을 벗어나 신세계를 누리는 방법인 프로미스
comments : true
---
오늘은 콜백지옥을 해소할 수 있는 **promise**에 대해 알아보았다.


### 콜백? (Callback?)
노드의 비동기처리는 단점이 되기도 하는데, 함수의 반환을 기다려주지 않는다는 점이다.  

다음은 mongoose 라이브러리 [^1] 를 사용한 예제이다.
```js
// User라는 모델 객체가 생성되어있다고 가정
function async() {
    const user = User.findOneById('id'); // 데이터베이스에서 raw를 찾아 반환

    console.log(user); // undefined
}

async();
```
`console.log()`함수로 user를 출력하는 때엔 `findOneById()`함수가 반환되지 않은 상태이다.  
따라서 user에는 그냥 undefined가 들어가게된다.

이래서 사용하는게 callback이다.
```js
function async() {
    User.findOneById('id', function(err, user){ // findOneById 함수의 인자로 모든 처리가 끝났을 때 실행할 함수(callback)를 전달
        console.log(user); // _id값이 'id'인 raw의 내용을 출력
    });
}

async();
```
`findOneById()`함수의 인자값으로 콜백함수를 넘겨줌으로써 모든 처리가 끝났을 때 해당 함수를 실행하도록 한다.  
따라서 _id값이 'id'인 raw의 내용을 정상적으로 출력하게된다.  

처음 보면 신선하고 효율적인 것처럼 보이지만 여기에는 큰 문제가 숨어있다.

### 콜백 지옥(CALLBACK HELL)
자 여기 물건중에서 상품명을 기준으로 물건을 검색하고, 이름을 기준으로 사람을 검색하고, 동아리 이름을 기준으로 동아리를 검색해서 반환하는 함수를 작성해보자.  
실제로 이런 처리를 할 일은 별로 없지만 마땅히 떠오르는 예제가 없다..  

#### callback hell -1
```js
function callbackHell(itemName, userName, circleName) {
    let result = {};
    Item.find({ "name": itemName }, function (err, items) {
        result.items = items;

        User.find({ "name": userName }, function (err, users) {
            result.users = users;

            Circle.find({ "name": circleName }, function (err, circles) {
                result.circles = circles;

                return result;
            })
        })
    })
}

callbackHell('연필','Terry','시나브로');
```
어떤가? 보기좋은 코드라고 생각하는가?  
함수안에서 `callbackHell()`함수같은 또 다른 함수를 호출하는 일이 잦다고 생각해보자. 게다가 이번엔 result 객체를 반환받아야한다!

#### callback hell - 2
```js
function callbackHell(itemName, userName, circleName, callback) { // 추가로 콜백함수를 받는다.
    let result = {};
    Item.find({ "name": itemName }, function (err, items) {
        result.items = items;

        User.find({ "name": userName }, function (err, users) {
            result.users = users;

            Circle.find({ "name": circleName }, function (err, circles) {
                result.circles = circles;

                callback(result); // 출력 대신 콜백함수로 원함수에 전달해준다.
            })
        })
    })
}

callbackHell('연필','Terry','시나브로', function(result){
    // 추가적인 가공없이 출력만 해보자.
    console.log(result);
});
```
아직도 괜찮은가? **그럼 그냥 그렇게 써라.**  
필자도 2개월 전까지는 더러운 코드를 짜왔기에 지금은 더 깔끔한 방법을 추천하고싶다.  

### Promise?
최근들어 많은 라이브러리가 새로운 문법인 `Promise`를 지원하기 시작했다.  
  
Promise가 무엇인지부터 알아보도록 하자.  

[MDN Web DOCS - Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)  

해당 문서에서는 Promise를 이렇게 정의하고있다.  
> `Promise`는 아직은 아니지만 나중에 완료될 것으로 기대되는 연산을 표현합니다.  
  
말그대로 정말 약속이다.  
예제로 이해하는게 더 빠르다.  

```js
function getPromise(n){
    return new Promise((resolve, reject)=>{
        if(n > 0) resolve(n * 10);
        else reject();
    });
}

getPromise(10) // 입력된 값이 양수라면 10을 곱해 반환하는 Promise를 반환한다.
.then((result)=>{ // resolve()호출시 then 속 함수가 실행된다.
    console.log(result);
})
.catch(()=>{ // reject() 호출시 catch 속 함수가 실행된다.
    console.log('PLZ INPUT NUMBER VALUE OVER 10');
})
```
이 프로그램을 표로 해석하면 이렇다.  
함수 | 기능
---|---
`getPromise(n)` | 인자로 수를 받아와 그 수가 양수일 경우 10을 곱해 반환하는 **Promise를 반환**한다.
`resolve()` |  처리가 완전히 끝났을 때 호출하는 함수이다. (사실 이름은 아무래도 상관없다. 하지만 통상적으로 사용하는 네이밍이니 지키는 것이 좋다.)
`reject()` | Promise 처리 과정에서 오류가 발생했을 때 (혹은 처리를 그만하고 싶은 때에) 호출하는 함수이다. 마찬가지로 이름은 상관없다.
`<Promise>.then(onResolve())` |  Promise에서 `resolve()`가 호출되었을 때 후속처리를 할 함수를 받아 프로미스의 리턴값과 함께 연결해주는 함수이다. 익명함수로 대체 가능하다.
`<Promise>.catch(onReject())`| Promise에서 `reject()`가 호출되었을 때 후속처리를 할 함수를 받아 프로미스의 리턴값과 함께 연결해주는 함수이다. 익명함수로 대체 가능하다.

현재 mongoose 라이브러리에서는 Promise를 지원한다. 내부적인 소스를 보았을 때 callback인자가 들어온다면 callback을 실행하고, 그렇지 않다면 **Promise객체를 반환**한다.  
이걸 위 callback hell 예제에 적용시켜보자.  

```js
function noMoreCallbackHell(itemName, userName, circleName){
    return new Promise((resolve, reject)=>{
        let result = {};
        Items.find({"name" : itemName})
        .then(items=>{
            result.items = items;
            return User.find({"name" : userName});
        })
        .then(users=>{
            result.users = users;
            return Circle.find({"name" : circleName});
        })
        .then(circles=>{
            result.circles = circles;

            resolve(result);
        })
        .catch(err=>{
            reject(err);
        })
    })
}

noMoreCallbackHell() // noMoreCallbackHell 함수 자체도 Promise를 반환하는것이다.
.then(result=>{ // noMoreCallbackHell 함수에서 resolve 함수를 호출했을 때 실행되는 구문이다.
    console.log("SUCCESSFULLY DONE");
    console.log(result);
})
.catch(err=>{ // noMoreCallbackHell 함수에서 reject 함수를 호출했을 때 실행되는 구문이다.
    console.log("ERROR HAS OCCURRED");
    console.log(err);
})
```

item 검색 -> user 검색 -> circle 검색이 순차적으로 이루어진다는 것을 확실하게 알아볼 수 있는 코드가 작성되었다.  
확실히 코드가 절차적으로 표현된다.  

이 밖에도 `Promise.all()` 등의 함수가 있지만 이는 MDN 문서[^2]에서 확인하는게 더 좋을 것 같다.

### 마치며..
오개념, 오탈자 등은 댓글로 제보해주시면 감사하겠습니다.  
앞으로는 글을 독백 형태로 적어나가겠습니다.  

---

### 주석
[^1]: mongoose 라이브러리 : <http://mongoosejs.com>  
[^2]: MDN-Promise : <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise>




